name = "edgetunnel"
main = "src/worker-vless.js"
compatibility_date = "2026-06-15"
compatibility_flags = [ "nodejs_compat" ]

[vars]
UUID = "ce16db6c-5a8a-4ccc-912b-8a5432787c18"
PROXYIP = "cdn.cloudflare.net"
