name = "edgetunnel"
main = "src/worker-vless.js"
compatibility_date = "2026-06-15"
compatibility_flags = [ "nodejs_compat" ]

[vars]
UUID = "28fe8443-1331-4108-a1a7-55ac225f8d8a"
PROXYIP = "cdn.cloudflare.net"
